# Ringrazio @aditya-wagh (https://stackoverflow.com/a/70628919) per LaTeX
# Ringrazio @peterevans (https://stackoverflow.com/a/58393457) per il commit

name: Aggiorna i file PDF
on:
  push:
    paths:
      - source/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Configura repository corrente
        uses: actions/checkout@v2

      - name: Compila il documento D1 (LaTeX)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 'Documento di progetto.tex'
          working_directory: source
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=..

      - name: Verifica la presenza e correttezza del D1
        run: |
          set -xe
          file 'Documento di progetto.pdf' | grep -q 'PDF'

      - name: Compila il documento D2 (LaTeX)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 'Documento dei requisiti.tex'
          working_directory: source
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=..

      - name: Verifica la presenza e correttezza del D2
        run: |
          set -xe
          file 'Documento dei requisiti.pdf' | grep -q 'PDF'
        
      - name: Compila il documento D3 (LaTeX)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 'Documento di architettura.tex'
          working_directory: source
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=..

      - name: Verifica la presenza e correttezza del D3
        run: |
          set -xe
          file 'Documento di architettura.pdf' | grep -q 'PDF'

      - name: Compila il documento D4 (LaTeX)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 'Documento di sviluppo.tex'
          working_directory: source
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=..

      - name: Verifica la presenza e correttezza del D4
        run: |
          set -xe
          file 'Documento di sviluppo.pdf' | grep -q 'PDF'

      - name: Carica i file aggiornati sulla repository
        run: |
          git config user.name 'Workflow Action'
          git config user.email 'x@x.x'
          git add .
          git commit -m 'Ricompilati i file PDF'
          git push
