# Ringrazio @aditya-wagh (https://stackoverflow.com/a/70628919) per LaTeX
# Ringrazio @peterevans (https://stackoverflow.com/a/58393457) per il commit

name: Aggiorna il file PDF
on:
  push:
    paths:
      - source/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Configura repository corrente
        uses: actions/checkout@v2

      - name: Compila il documento LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: 'Documento di progetto.tex'
          working_directory: source
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=..

      - name: Verifica la presenza e correttezza del file
        run: |
          set -xe
          file 'Documento di progetto.pdf' | grep -q 'PDF'

      - name: Carica il file aggiornato sulla repository
        run: |
          git config user.name 'Workflow Action'
          git config user.email 'x@x.x'
          git add .
          git commit -m 'Ricompilato il file PDF'
          git push
