# Ringrazio @aditya-wagh (https://stackoverflow.com/a/70628919) per LaTeX
# Ringrazio @peterevans (https://stackoverflow.com/a/58393457) per il commit

name: Aggiorna il file PDF
on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

    - name: Configura repository corrente
      uses: actions/checkout@v2

    - name: Compila il documento LaTeX
      uses: xu-cheng/latex-action@v2
      with:
          root_file: "Documento di progetto.tex"
          working_directory: source

          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

    - name: Verifica la presenza del file e spostalo nella cartella principale
      run: |
        file 'source/Documento di progetto.pdf' | grep -q ' PDF '
        mv 'source/Documento di progetto.pdf' .

    - name: Carica il file aggiornato sulla repository
      run: |
        git config --global user.name "silvanusbordignon"
        git config --global user.email "silvanusbordignon@gmail.com"
        git add "Documento di progetto.pdf"
        git commit -m "Workflow: Aggiorna il file PDF"
        git push
